#name: note_taker
#description: "Store Visit Management Application"
#publish_to: 'none'
#version: 1.0.0+1
#
#environment:
#  sdk: '>=3.0.0 <4.0.0'
#  flutter: ">=3.0.0"
#
#dependencies:
#  flutter:
#    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
#
#  # UI Components
#  cupertino_icons: ^1.0.2
#
#  # State Management
#  provider: ^6.0.5
#
#  # Storage
#  shared_preferences: ^2.2.2
#  path_provider: ^2.1.1
#  path: ^1.8.3
#
#  # Features
#  image_picker: ^1.0.4
#  geolocator: ^10.1.0
#  permission_handler: ^11.0.1
#  share_plus: ^7.2.1
#
#  # Data Handling
#  excel: ^2.1.0
#  json_annotation: ^4.8.1
#  intl: ^0.19.0
#  uuid: ^4.0.0
#
#  # Images
#  image: ^4.1.3
#  cached_network_image: ^3.3.0
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^2.0.0
#  build_runner: ^2.4.6
#  json_serializable: ^6.7.1
#  flutter_launcher_icons: ^0.13.1
#
## Flutter Launcher Icons configuration
#flutter_launcher_icons:
#  android: true
#  ios: true
#  image_path: "assets/icon/icon.png"
#  adaptive_icon_background: "#ffffff"
#  adaptive_icon_foreground: "assets/icon/icon.png"
#  min_sdk_android: 21
#  remove_alpha_ios: true
#  web:
#    generate: true
#    image_path: "assets/icon/icon.png"
#  windows:
#    generate: true
#    image_path: "assets/icon/icon.png"
#  macos:
#    generate: true
#    image_path: "assets/icon/icon.png"
#
#flutter:
#  uses-material-design: true
#
#  assets:
#    - assets/icon/



name: visilog  # Change from note_taker (must be lowercase)
description: "Store Visit Management Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.0.5

  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.8.3

  # Features
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  share_plus: ^7.2.1

  # Data Handling
  excel: ^2.1.0
  json_annotation: ^4.8.1
  intl: ^0.19.0
  uuid: ^4.0.0

  # Images
  image: ^4.1.3
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png